<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-0AG0V8V" ignored="0" name="Test" tests="8" failures="1" timestamp="29 Oct 2019 02:14:19 GMT" time="0.16" errors="0">
  <testcase name="test1" time="0.009" classname="com.TestNGListeners.SampleTest"/>
  <testcase name="test2" time="0.003" classname="com.TestNGListeners.SampleTest">
    <failure type="org.testng.TestException" message="
Method SampleTest.test2()[pri:0, instance:com.TestNGListeners.SampleTest@27efef64] should have thrown an exception of type class java.lang.RuntimeException">
      <![CDATA[org.testng.TestException: 
Method SampleTest.test2()[pri:0, instance:com.TestNGListeners.SampleTest@27efef64] should have thrown an exception of type class java.lang.RuntimeException
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase name="test3" time="0.003" classname="com.TestNGListeners.SampleTest">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase name="test4" time="0.011" classname="com.TestNGListeners.SampleTest"/>
  <testcase name="test4" time="0.002" classname="com.TestNGListeners.SampleTest"/>
  <testcase name="test4" time="0.004" classname="com.TestNGListeners.SampleTest"/>
  <testcase name="test4" time="0.002" classname="com.TestNGListeners.SampleTest"/>
  <testcase name="test4" time="0.002" classname="com.TestNGListeners.SampleTest"/>
</testsuite> <!-- Test -->
